// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHRpTXfays92OlkpH1OoYNjB1nB5mZkWk',
    appId: '1:102421210212:web:eac2640951b63ed35eeb71',
    messagingSenderId: '102421210212',
    projectId: 'amazespa-f9b6e',
    authDomain: 'amazespa-f9b6e.firebaseapp.com',
    storageBucket: 'amazespa-f9b6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKKZyVhaZ3DLwg__g-sKBz9MK7J9cnKv4',
    appId: '1:102421210212:android:04ea4d9cb51a37125eeb71',
    messagingSenderId: '102421210212',
    projectId: 'amazespa-f9b6e',
    storageBucket: 'amazespa-f9b6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-YrApgaGsmZekGRWA3RMX0WGxMY7mI30',
    appId: '1:102421210212:ios:49e2ec4ba74267925eeb71',
    messagingSenderId: '102421210212',
    projectId: 'amazespa-f9b6e',
    storageBucket: 'amazespa-f9b6e.appspot.com',
    iosClientId: '102421210212-bkb1ac68t95q3koacbnessjvk63qeqsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazespa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-YrApgaGsmZekGRWA3RMX0WGxMY7mI30',
    appId: '1:102421210212:ios:49e2ec4ba74267925eeb71',
    messagingSenderId: '102421210212',
    projectId: 'amazespa-f9b6e',
    storageBucket: 'amazespa-f9b6e.appspot.com',
    iosClientId: '102421210212-bkb1ac68t95q3koacbnessjvk63qeqsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazespa',
  );
}
